### ISSUE TITLE
Icon branch not building in modern

### ISSUE THREAD

**Issue by Jaizu** [aarant/pokeemerald#12]
Unaligned stuff!
Fixed with:
`static const u16 ALIGNED(4) sHandCursor_Pal[] = INCBIN_U16("graphics/pokemon_storage/hand_cursor.gbapal");`
and
`u16 ALIGNED(4) chooseBoxSwapPal[16]; // Holds dynamic palette to swap into choose box gfx`

**Comment by aarant** [comment]
Closed in #14
