### ISSUE TITLE
[Guillotine] PC not properly decap

### ISSUE THREAD

**Issue by Jaizu** [aarant/pokeemerald#25]
Should be PC
![image](https://github.com/aarant/pokeemerald/assets/18596778/a00a3301-8b96-45a5-844a-538950a63a35)

**Comment by aarant** [comment]
Closed in aef28b7

**Comment by Jaizu** [comment]
![image](https://github.com/aarant/pokeemerald/assets/18596778/08da5d96-864e-462b-a1ed-98e33acda967)
This is not fixed, should be re-opened.

**Comment by aarant** [comment]
I forgot to add `.` as a separator, sorry

**Comment by aarant** [comment]
Closed in 0de9046
