### ISSUE TITLE
"Yellow mode" for overworld pokemon

### ISSUE THREAD

**Issue by kittenchilly** [aarant/pokeemerald#42]
This would be a config option that when true, only looks for some sort of "main follower" data assigned and given to a specific pokemon (i.e. a starter). This main follower would be the only pokemon that can spawn and follow the player in the overworld, and it would appear when in any slot of the party, not just the first slot. Basically mimics the behavior of the starter Pikachu in Pokemon Yellow.

**Comment by aarant** [comment]
Closed in [3fffb9f](https://github.com/aarant/pokeemerald/commit/3fffb9fac6c3eb9c232609565f5e84957630a32c)
