### ISSUE TITLE
Showmonpic affected by day and night tints

### ISSUE THREAD

**Issue by Jaizu** [aarant/pokeemerald#8]
![image](https://github.com/aarant/pokeemerald/assets/18596778/8d4b062e-7e8b-4e17-a9ac-43fd5d18f54e)

I'm pretty sure that this is related to the follower sprite being loaded in the overworld, so they share the same palette, I think?
This was not really discovered before since this is a case that might happen in Kanto and not Hoenn.

**Comment by aarant** [comment]
Fixed in 05a6147
