### ISSUE TITLE
Small graphical bug from the key wheel when using the vs seeker

### ISSUE THREAD

**Issue by Jaizu** [aarant/pokeemerald#9]
No idea how to properly report this, I'm sure there is something that just doesnt stay like the overworld was before using the key wheel, not sure if the text windows, blocks loaded in the bg or whatever, I will try to investigate more

https://github.com/aarant/pokeemerald/assets/18596778/cc68a888-84d1-4df5-8475-ac6f134a397b

**Comment by aarant** [comment]
Fixed in #11
